services:
  postgres-usuarios:
    image: postgres:17
    container_name: sicae-postgres-usuarios
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data
      - ./bd/user:/docker-entrypoint-initdb.d/
    networks:
      - sicae-red

  mysql-vehiculos:
    image: mysql:8.0
    container_name: sicae-mysql-vehiculos
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_VEHICULOS_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysql_vehiculos_data:/var/lib/mysql
      - ./bd/vehicle:/docker-entrypoint-initdb.d/
    networks:
      - sicae-red

  mysql-estacionamiento:
    image: mysql:8.0
    container_name: sicae-mysql-estacionamiento
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_ESTACIONAMIENTO_DB}
    ports:
      - "3308:3306"
    volumes:
      - mysql_estacionamiento_data:/var/lib/mysql
      - ./bd/parking:/docker-entrypoint-initdb.d/
    networks:
      - sicae-red

  microservicio-usuario:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: sicae-microservicio-usuario
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8081:8081"
    depends_on:
      - postgres-usuarios
    networks:
      - sicae-red

  microservicio-vehiculos:
    build:
      context: ./vehicles
      dockerfile: Dockerfile
    container_name: sicae-microservicio-vehiculos
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_VEHICULOS_DB: ${MYSQL_VEHICULOS_DB}
    ports:
      - "8082:8082"
    depends_on:
      - mysql-vehiculos
    networks:
      - sicae-red

  microservicio-estacionamiento:
    build:
      context: ./parking
      dockerfile: Dockerfile
    container_name: sicae-microservicio-estacionamiento
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_ESTACIONAMIENTO_DB: ${MYSQL_ESTACIONAMIENTO_DB}
    ports:
      - "8083:8083"
    depends_on:
      - mysql-estacionamiento
    networks:
      - sicae-red

volumes:
  postgres_usuarios_data:
  mysql_vehiculos_data:
  mysql_estacionamiento_data:

networks:
  sicae-red:
    driver: bridge
